[build]
  publish = "build" # Directory where your build artifacts are generated
  command = "npm run build" # Command to create the production build

[dev]
  command = "npm start" # Command to run your app locally (for Netlify Dev)